package com.example.maslakotlin
fun main()
{
    println("Student 1: ")
    var St = Student(1000, "Ali Raza", "Faisal Town 789", 302198999, "Unemployed", 1, "CS", 2019, 6, "FAST", 2)
    St.print()
    println(St.register("SMD"))
    println(St.learn())
    println(St.attend("SMD"))
    println("Student Grade: ")
    println("Grade is " + St.get_grade("SMD"))
    println(" ")
    println("Staff 1:")
    var p=Student(1000, "Fida Raath", "Faisal Town 789", 302198999, "Unemployed", 1, "CS", 2019, 6, "FAST", 2)
    var Stf = Staff(11, "Faez", "BOR Road", 32336788, "Technician", "Emp 1", "Technician", "Electrical Engineering Department", 50000.0)
    println(Stf.register("NULL"))
    println("Salary in Rs: ")
    println(Stf.getSalary())
    println(Stf.attend("Lab Duty"))
    println(Stf.getPromotion())
    println(" ")

    println("PG Student 1: ")
    var Pg = PG_Student("18L-1004", "Data Science", 11, "Ali", "Faisal Town Block B", 32336789, "Student", 2, "DS", 2018, 5, "FAST", 3)
    println(Pg.submitthesis())
    println(" ")

    println("Technician 1: ")
    var tech = Technician("Lab Tech", 12, "Ahmed","Faisal Town Block A", 98766778, "Technician", "Emp 2", "Tch",  "Rs. 15000", 20000.0, 5)
    println(tech.install("Workstation"))
    println(tech.mantain("CS1"))
    println(" ")

    println("Faculty 1: ")
    var teach = Faculty("CS", "A", 60, "Phd", 13, "Sir", "teacher address", 97789, "Teacher", "Emp1", "Teacher", "0.0", 60000.00, 2 )
    println(teach.teach("SMD"))
    println(teach.assess(4))

    //Question 2
    var a:Bowler = BowlerImplem(100,2, "Hamza", 19,"Pakistani")
    a.print()
    println("Bowler Ranking: ")
    println(a.getranking())
    var ar:AllRounder = allRounderImplem(1,26,19,154,37,a.name,a.age,a.nationality)
    ar.print()
    println("All Rounder Ranking: ")
    println(ar.getranking())
    var b:Batsman = BatsmanImplem(600, 18, "Abdullah", 23, "Pakistani")
    println("Batsman Ranking: ")
    println(b.getranking())
    b.print()
}